# Generated by Django 6.0.3 on 2026-03-23 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='author',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
    ]
